### ISSUE TITLE
AssertionError: v has been set as a member variable

### ISSUE THREAD

**Issue by ChidanandKumarKS** [LinZhu111/EVSNN#3]
@LinZhu111
Thanks for your repo.
When i execute any of scripts
python rec_snn.py -network EVSNN_LIF_final -path_to_pretrain_models ./pretrained_models/EVSNN.pth
or
python rec_snn.py -network PAEVSNN_LIF_AMPLIF_final -path_to_pretrain_models ./pretrained_models/PAEVSNN.pth

iam getting error below. Kindly help

File "/home/EVSNN-main/neurons/spiking_neuron.py", line 231, in forward
self.register_memory('v', last_mem)
File "/home/anaconda3/envs/event_work_seg/lib/python3.6/site-packages/spikingjelly/clock_driven/base.py", line 50, in register_memory
assert not hasattr(self, name), f'{name} has been set as a member variable'
AssertionError: v has been set as a member variable

**Comment by LinZhu111** [comment]
Thank you for your interest in our work.
You can try installing version 0.0006 of spikingjelly as follows:
pip install spikingjelly==0.0.0.0.6

**Comment by ChidanandKumarKS** [comment]
Thanks bro @LinZhu111 . Its versioning issue only as i was using 0.0.0.0.8 rather 0.6
